(() => {
  'use strict';
  const SETTINGS_KEY='pb:settings';
  const RULE_PREFIX='rule:';
  const DOMAIN_PREFIX='idx:domain:';
  const PAGE_PREFIX='idx:page:';
  const ATTR='data-progettoblur-rule-id';
  const STYLE_ID='pb-rule-style';
  const HIGHLIGHT='pb-selection-highlight';
  const RULE_FOCUS='pb-rule-focus';
  const EFFECTS=['blur','strongBlur','pixelate','blackout','hide'];
  const applied=new Map();
  const original=new WeakMap();
  let selection=false,hover=null,focused=null;
  let settings={extensionEnabled:true,selectionEffect:'blur',selectionIntensity:60};
  let settingsReady=false;
  let selectionQueue=Promise.resolve();
  const selectionCreated=new Set();
  let rulesCache=null;
  let rulesContext='';
  let evaluateTimer=null;
  let evaluating=false;
  let evaluateAgain=false;
  const suppressed=new Set();
  const ctx=()=>({domain:location.hostname,path:location.pathname||'/'});
  const ctxKey=()=>`${location.hostname}|${location.pathname||'/'}`;
  const ruleKey=id=>`${RULE_PREFIX}${id}`;
  const domainKey=d=>`${DOMAIN_PREFIX}${d}`;
  const pageKey=(d,p)=>`${PAGE_PREFIX}${d}:${p}`;
  const stable=v=>{const s=String(v||'').trim();return !!s&&!/^[a-f0-9]{8}-[a-f0-9-]{27,}$/i.test(s)&&!/^[a-f0-9]{10,}$/i.test(s)&&!/(\d{9,}|\d{4,}_\d{4,})$/.test(s)};
  const tokens=v=>String(v||'').split(/\s+/).map(x=>x.trim()).filter(stable);
  const norm=v=>String(v||'').replace(/\s+/g,' ').trim().slice(0,1200);
  const escape=s=>CSS.escape(String(s));
  async function getSettings(){if(settingsReady)return settings;const r=await chrome.storage.local.get({[SETTINGS_KEY]:settings});settings={...settings,...(r[SETTINGS_KEY]||{})};settingsReady=true;return settings}
  async function getRule(id){const r=await chrome.storage.local.get({[ruleKey(id)]:null});return r[ruleKey(id)]||null}
  async function getRules(){const k=ctxKey();if(rulesCache&&rulesContext===k)return rulesCache;const c=ctx();const r=await chrome.storage.local.get({[domainKey(c.domain)]:[],[pageKey(c.domain,c.path)]:[]});const ids=[...new Set([...(r[domainKey(c.domain)]||[]),...(r[pageKey(c.domain,c.path)]||[])])];const loaded=ids.length?await chrome.storage.local.get(ids.map(ruleKey)):{};rulesCache=ids.map(id=>loaded[ruleKey(id)]).filter(Boolean).filter(x=>x.frameKey?x.frameKey===frameKey():frameKey()==='top');rulesContext=k;return rulesCache}
  function invalidate(){rulesCache=null;rulesContext=''}
  function frameDescriptor(frame){const tag=(frame?.tagName||'iframe').toLowerCase(),id=String(frame?.id||'').trim(),name=String(frame?.name||'').trim();if(id)return `${tag}#${id}`;if(name)return `${tag}[name=${name}]`;const p=frame?.parentElement,s=p?[...p.children].filter(x=>x.tagName===frame.tagName):[];return `${tag}[n=${Math.max(0,s.indexOf(frame))}]`}
  function frameKey(){const chain=[];try{let w=window;while(w!==w.top){const f=w.frameElement;if(!f)return null;chain.unshift(frameDescriptor(f));w=w.parent}return chain.length?`frame:${chain.join('/')}`:'top'}catch(_){return null}}
  function cssPath(el){if(el.id&&stable(el.id))return `#${escape(el.id)}`;const parts=[];let n=el,depth=0;while(n instanceof Element&&n!==document.documentElement&&depth++<10){let p=n.tagName.toLowerCase();const cls=tokens(n.className).slice(0,2);if(cls.length)p+=`.${cls.map(escape).join('.')}`;const parent=n.parentElement;if(parent){const same=[...parent.children].filter(x=>x.tagName===n.tagName);if(same.length>1)p+=`:nth-of-type(${same.indexOf(n)+1})`}parts.unshift(p);n=parent}return parts.join('>')}
  function syncFingerprint(el){const attrs=[];for(const a of el.attributes||[]){if(/^(data-|aria-|name$|role$|type$|inputmode$|rel$|target$)/i.test(a.name)&&a.value)attrs.push({name:a.name.toLowerCase(),value:a.value.toLowerCase()})}const parent=el.parentElement;const siblings=parent?[...parent.children]:[];return {version:'2.0',cssSelector:cssPath(el),stableId:stable(el.id)?el.id:undefined,stableClasses:tokens(el.className),tagName:el.tagName.toLowerCase(),semanticAttributes:attrs,text:norm(el.textContent),parentTag:parent?.tagName.toLowerCase(),parentClasses:tokens(parent?.className),siblingIndex:siblings.indexOf(el)}}
  function sameAttrs(fp,el){return (fp.semanticAttributes||[]).filter(a=>el.getAttribute(a.name)?.toLowerCase()===a.value).length}
  function candidateScore(fp,el){let score=0,ind=0;if(fp.stableId&&el.id===fp.stableId){score+=.45;ind++}const cls=(fp.stableClasses||[]);if(cls.length){const hit=cls.filter(c=>tokens(el.className).includes(c)).length/cls.length;if(hit>=.65){score+=.18;ind++}}const attrs=fp.semanticAttributes||[];if(attrs.length){const hit=sameAttrs(fp,el)/attrs.length;if(hit>=.65){score+=.18;ind++}}if(fp.tagName===el.tagName.toLowerCase())score+=.05;if(fp.parentTag===el.parentElement?.tagName.toLowerCase())score+=.05;if(Number.isInteger(fp.siblingIndex)&&fp.siblingIndex===[...(el.parentElement?.children||[])].indexOf(el)){score+=.07;ind++}if(fp.text&&norm(el.textContent)===fp.text&&fp.text.length<=600){score+=.08;ind++}return {score:Math.min(1,score),independent:ind}}
  function uniqueSelectorCandidate(fp){if(!fp.cssSelector)return null;try{const all=[...document.querySelectorAll(fp.cssSelector)];return all.length===1?all[0]:null}catch(_){return null}}
  async function matchRule(rule,forFocus=false){const fp=rule.fingerprint||{};const direct=uniqueSelectorCandidate(fp);if(direct&&direct.tagName.toLowerCase()===fp.tagName){const s=candidateScore(fp,direct);if(forFocus||rule.scope==='page')return {status:'active',confidence:Math.max(.9,s.score),selected:direct,independent:Math.max(3,s.independent)}}const candidates=[];const seen=new Set();const add=list=>{for(const el of list){if(!seen.has(el)){seen.add(el);candidates.push(el)}}};if(fp.stableId){try{add(document.querySelectorAll(`#${escape(fp.stableId)}`))}catch(_) {}}for(const a of fp.semanticAttributes||[]){try{add(document.querySelectorAll(`[${escape(a.name)}="${CSS.escape(a.value)}"]`))}catch(_) {}}if(fp.cssSelector){try{add(document.querySelectorAll(fp.cssSelector))}catch(_) {}}if(!candidates.length&&fp.tagName)add(document.getElementsByTagName(fp.tagName));let best=null,second=null;for(const el of candidates){const s=candidateScore(fp,el);const item={...s,element:el};if(!best||item.score>best.score){second=best;best=item}else if(!second||item.score>second.score)second=item}if(!best||best.score<.45)return {status:'notFound',confidence:best?.score||0,selected:best};const gap=second?best.score-second.score:1;if(best.score>=.72&&best.independent>=2&&gap>.05)return {status:'active',confidence:best.score,selected:best};return {status:'ambiguous',confidence:best.score,selected:best}}
  function ensureStyle(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent='.pb-effect-base{transition:filter 120ms ease}.pb-effect-blur{filter:blur(var(--pb-blur,6px))!important}.pb-effect-strongBlur{filter:blur(var(--pb-strong-blur,16px))!important}.pb-effect-pixelate{filter:blur(8px) contrast(1.8)!important}.pb-effect-blackout{filter:brightness(0)!important;color:transparent!important;text-shadow:none!important}.pb-effect-hide{visibility:hidden!important}';(document.head||document.documentElement).appendChild(s)}
  function apply(el,rule){if(!(el instanceof Element))return;ensureStyle();if(!original.has(el))original.set(el,{filter:el.style.filter,visibility:el.style.visibility,color:el.style.color,textShadow:el.style.textShadow,blur:el.style.getPropertyValue('--pb-blur'),strong:el.style.getPropertyValue('--pb-strong-blur')});['blur','strongBlur','pixelate','blackout','hide'].forEach(x=>el.classList.remove(`pb-effect-${x}`));const i=Math.max(0,Math.min(100,Number(rule.intensity??60)));el.classList.add('pb-effect-base',`pb-effect-${EFFECTS.includes(rule.effect)?rule.effect:'blur'}`);el.style.setProperty('--pb-blur',`${Math.max(1,Math.round(i*.12))}px`);el.style.setProperty('--pb-strong-blur',`${Math.max(4,Math.round(i*.28))}px`);el.setAttribute(ATTR,rule.ruleId);applied.set(rule.ruleId,el)}
  function removeEl(el){if(!(el instanceof Element))return;el.classList.remove(RULE_FOCUS,'pb-effect-base',...EFFECTS.map(x=>`pb-effect-${x}`));const o=original.get(el);if(o){o.filter?el.style.setProperty('filter',o.filter):el.style.removeProperty('filter');o.visibility?el.style.setProperty('visibility',o.visibility):el.style.removeProperty('visibility');o.color?el.style.setProperty('color',o.color):el.style.removeProperty('color');o.textShadow?el.style.setProperty('text-shadow',o.textShadow):el.style.removeProperty('text-shadow');o.blur?el.style.setProperty('--pb-blur',o.blur):el.style.removeProperty('--pb-blur');o.strong?el.style.setProperty('--pb-strong-blur',o.strong):el.style.removeProperty('--pb-strong-blur');original.delete(el)}el.removeAttribute(ATTR)}
  function removeRule(id){const el=applied.get(id);if(el)removeEl(el);applied.delete(id)}
  function focusElement(el){if(!el)return false;if(focused)focused.classList.remove(RULE_FOCUS);focused=el;el.classList.add(RULE_FOCUS);try{el.scrollIntoView({behavior:'smooth',block:'center',inline:'nearest'})}catch(_){el.scrollIntoView()}return true}
  async function focusRule(id){const rule=await getRule(id);if(!rule)return false;if(applied.has(id))return focusElement(applied.get(id));const r=await matchRule(rule,true);if(r.status==='active'&&r.selected){apply(r.selected,rule);return focusElement(r.selected)}return false}
  function target(node){if(!(node instanceof Element)||node.closest('[data-progettoblur-ui="true"]')||node.id===STYLE_ID)return null;return node}
  function onMove(e){const el=target(e.target);if(!el)return;if(hover&&hover!==focused)hover.classList.remove(HIGHLIGHT);hover=el;hover.classList.add(HIGHLIGHT)}
  function onClick(e){const el=target(e.target);if(!selection||!el||el.tagName==='IFRAME'||el.closest(`[${ATTR}]`))return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();selectionQueue=selectionQueue.then(async()=>{if(!selection)return;const c=ctx(),now=new Date().toISOString(),st=await getSettings();const rule={ruleId:`rule-${crypto.randomUUID()}`,scope:'page',domain:c.domain,path:c.path,url:location.href,frameKey:frameKey()||'unknown',enabled:true,status:'active',effect:EFFECTS.includes(st.selectionEffect)?st.selectionEffect:'blur',intensity:Math.max(0,Math.min(100,Number(st.selectionIntensity??60))),createdAt:now,updatedAt:now,fingerprint:syncFingerprint(el)};selectionCreated.add(rule.ruleId);apply(el,rule);invalidate();try{const d=domainKey(rule.domain),p=pageKey(rule.domain,rule.path);const old=await chrome.storage.local.get({[d]:[],[p]:[]});await chrome.storage.local.set({[ruleKey(rule.ruleId)]:rule,[d]:[...(old[d]||[]),rule.ruleId],[p]:[...(old[p]||[]),rule.ruleId]});}catch(_){} })}
  function startSelection(){selection=false;stopListeners();selectionCreated.clear();selection=true;document.addEventListener('mousemove',onMove,true);document.addEventListener('click',onClick,true)}
  function stopListeners(){document.removeEventListener('mousemove',onMove,true);document.removeEventListener('click',onClick,true);if(hover&&hover!==focused)hover.classList.remove(HIGHLIGHT);hover=null}
  function stopSelection(){const was=selection;selection=false;stopListeners();if(was){selectionCreated.clear();scheduleEvaluate(0)}}
  addEventListener('keydown',e=>{if(selection&&e.key==='Escape'){e.preventDefault();e.stopPropagation();stopSelection()}},true);
  async function evaluateRule(rule){if(!rule.enabled||!(await getSettings()).extensionEnabled||suppressed.has(rule.ruleId)){removeRule(rule.ruleId);return {status:'disabled',confidence:0}}if(rule.frameKey&&rule.frameKey!==(frameKey()||'unknown')){removeRule(rule.ruleId);return {status:'notApplicable',confidence:0}}if(selection&&selectionCreated.has(rule.ruleId)&&applied.has(rule.ruleId))return {status:'active',confidence:1};const r=await matchRule(rule,false);if(r.status==='active'&&r.selected){apply(r.selected,rule)}else if(!selectionCreated.has(rule.ruleId))removeRule(rule.ruleId);return r}
  async function evaluateAll(){if(evaluating){evaluateAgain=true;return}evaluating=true;try{const rules=await getRules();for(const r of rules)await evaluateRule(r)}finally{evaluating=false;if(evaluateAgain){evaluateAgain=false;scheduleEvaluate(0)}}}
  function scheduleEvaluate(ms=30){clearTimeout(evaluateTimer);evaluateTimer=setTimeout(evaluateAll,ms)}
  chrome.runtime.onMessage.addListener((m,_s,send)=>{(async()=>{switch(m?.type){case'BG_ENTER_SELECTION':startSelection();return send({ok:true,selectionActive:true});case'BG_EXIT_SELECTION':stopSelection();return send({ok:true,selectionActive:false});case'BG_FOCUS_RULE':return send({ok:true,result:await focusRule(m.ruleId)});case'BG_REMOVE_RULE_EFFECT_PAGE':suppressed.add(m.ruleId);removeRule(m.ruleId);return send({ok:true});case'BG_REMOVE_ALL_EFFECTS_PAGE':(await getRules()).forEach(r=>suppressed.add(r.ruleId));applied.forEach((_,id)=>removeRule(id));return send({ok:true});case'BG_RETRY_RULE_ON_PAGE':suppressed.delete(m.ruleId);{const r=await getRule(m.ruleId);if(r)await evaluateRule(r);return send({ok:true})}case'POPUP_DISABLE_RULE':{const r=await getRule(m.ruleId);if(r){r.enabled=false;r.status='disabled';await chrome.storage.local.set({[ruleKey(r.ruleId)]:r});removeRule(r.ruleId)}return send({ok:true})}case'POPUP_ENABLE_RULE':{const r=await getRule(m.ruleId);if(r){r.enabled=true;r.status='active';suppressed.delete(r.ruleId);await chrome.storage.local.set({[ruleKey(r.ruleId)]:r});await evaluateRule(r)}return send({ok:true})}case'POPUP_DELETE_RULE':suppressed.delete(m.ruleId);removeRule(m.ruleId);{const r=await getRule(m.ruleId);if(r){const d=domainKey(r.domain),p=pageKey(r.domain,r.path);const idx=await chrome.storage.local.get({[d]:[],[p]:[]});await chrome.storage.local.set({[d]:(idx[d]||[]).filter(x=>x!==m.ruleId),[p]:(idx[p]||[]).filter(x=>x!==m.ruleId)});await chrome.storage.local.remove(ruleKey(m.ruleId))}invalidate();return send({ok:true})}case'CONTENT_GET_STATE':{const st=await getSettings();return send({ok:true,extensionEnabled:st.extensionEnabled!==false,selectionActive:selection,rules:await getRules()})}default:return send({ok:true})}})().catch(e=>send({ok:false,error:String(e?.message||e)}));return true});
  chrome.storage.onChanged.addListener(ch=>{if(ch[SETTINGS_KEY]){settings={...settings,...(ch[SETTINGS_KEY].newValue||{})};settingsReady=true;if(settings.extensionEnabled===false){applied.forEach((_,id)=>removeRule(id))}else if(!selection)scheduleEvaluate(0)}if(Object.keys(ch).some(k=>k.startsWith(RULE_PREFIX)||k.startsWith('idx:'))){invalidate();if(!selection)scheduleEvaluate(0)}});
  const obs=new MutationObserver(muts=>{let added=false;for(const m of muts)if(m.type==='childList'&&m.addedNodes.length)added=true;if(added&&!selection)scheduleEvaluate(40)});if(document.documentElement)obs.observe(document.documentElement,{childList:true,subtree:true});
  addEventListener('popstate',()=>{invalidate();suppressed.clear();scheduleEvaluate(0)},true);
  for(const n of ['pushState','replaceState']){const f=history[n];if(f.__stayBlurWrapped)continue;const w=function(...a){const before=location.href,r=f.apply(this,a);if(location.href!==before){invalidate();suppressed.clear();stopSelection();scheduleEvaluate(0)}return r};Object.defineProperty(w,'__stayBlurWrapped',{value:true});history[n]=w}
  globalThis.__progettoBlurStartSelection=startSelection;globalThis.__progettoBlurStopSelection=stopSelection;getSettings().then(()=>evaluateAll()).catch(()=>{});
})();
