(() => {
  'use strict';
  const SETTINGS_KEY = 'pb:settings';
  const RULE_PREFIX = 'rule:';
  const DOMAIN_PREFIX = 'idx:domain:';
  const PAGE_PREFIX = 'idx:page:';
  const ATTR = 'data-progettoblur-rule-id';
  const STYLE_ID = 'pb-rule-style';
  const HIGHLIGHT = 'pb-selection-highlight';
  const INDICATOR_ID = 'pb-selection-indicator';
  const MAX_CANDIDATES = 1000;
  const RETRY_DELAYS = [25, 75, 150, 300, 600];
  const INTEGRITY_ATTRS = ['class', 'style', 'id', 'hidden'];
  const WEIGHTS = { stableId: .26, semanticAttributes: .22, textHash: .14, stableClasses: .12, ancestorContext: .10, structureContext: .08, cssSelector: .04, geometry: .02, tagName: .02 };
  const INDEPENDENT = ['stableId', 'semanticAttributes', 'textHash', 'stableClasses', 'ancestorContext', 'structureContext'];
  const SAFETY_MIN_CONFIDENCE = .85;
  const SAFETY_MIN_INDEPENDENT = 3;
  const EFFECT_CLASSES = ['pb-effect-base', 'pb-effect-blur', 'pb-effect-strongBlur', 'pb-effect-pixelate', 'pb-effect-blackout', 'pb-effect-hide'];
  const keyRule = id => `${RULE_PREFIX}${id}`;
  const keyDomain = d => `${DOMAIN_PREFIX}${d}`;
  const keyPage = (d, p) => `${PAGE_PREFIX}${d}:${p}`;
  const context = () => ({ domain: location.hostname, path: location.pathname || '/' });
  const contextKey = () => `${location.hostname}|${location.pathname || '/'}`;
  function frameDescriptor(frame) { const tag = (frame?.tagName || 'iframe').toLowerCase(); const id = typeof frame?.id === 'string' ? frame.id.trim() : ''; const name = typeof frame?.name === 'string' ? frame.name.trim() : ''; const parent = frame?.parentElement; const siblings = parent ? [...parent.children].filter(el => el.tagName === frame.tagName) : []; const siblingIndex = siblings.indexOf(frame); if (id) return `${tag}#${id}`; if (name) return `${tag}[name=${name}]`; return `${tag}[n=${siblingIndex >= 0 ? siblingIndex : '?'}]`; }
  function frameContextKey() { const chain = []; try { let currentWindow = window; while (currentWindow !== currentWindow.top) { const frame = currentWindow.frameElement; if (!frame || frame.nodeType !== 1) return null; chain.unshift(frameDescriptor(frame)); currentWindow = currentWindow.parent; } } catch (_) { return null; } return chain.length ? `frame:${chain.map((part, depth) => `${depth}:${part}`).join('/')}` : 'top'; }
  function ruleAppliesToCurrentFrame(rule) { const current = frameContextKey(); if (!current) return false; return rule.frameKey ? rule.frameKey === current : current === 'top'; }
  let settingsCache = { extensionEnabled: true, selectionEffect: 'blur', selectionIntensity: 60 }, settingsReady = false, rulesCache = null, rulesCacheContext = '', rulesLoad = null;
  async function getSettings() { if (settingsReady) return settingsCache; const r = await chrome.storage.local.get({ [SETTINGS_KEY]: { extensionEnabled: true, selectionEffect: 'blur', selectionIntensity: 60 } }); settingsCache = { extensionEnabled: true, selectionEffect: 'blur', selectionIntensity: 60, ...(r[SETTINGS_KEY] || {}) }; settingsReady = true; return settingsCache; }
  async function getRule(id) { const r = await chrome.storage.local.get({ [keyRule(id)]: undefined }); return r[keyRule(id)]; }
  async function getRules() { const ck = contextKey(); if (rulesCache && rulesCacheContext === ck) return rulesCache; if (rulesLoad && rulesLoad.context === ck) return rulesLoad.promise; const promise = (async () => { const c = context(); const r = await chrome.storage.local.get({ [keyDomain(c.domain)]: [], [keyPage(c.domain, c.path)]: [] }); const ids = [...new Set([...(r[keyDomain(c.domain)] || []), ...(r[keyPage(c.domain, c.path)] || [])])]; if (!ids.length) return []; const loaded = await chrome.storage.local.get(ids.map(keyRule)); return ids.map(id => loaded[keyRule(id)]).filter(Boolean).filter(ruleAppliesToCurrentFrame); })(); rulesLoad = { context: ck, promise }; const result = await promise; if (rulesLoad?.promise === promise) rulesLoad = null; if (contextKey() === ck) { rulesCache = result; rulesCacheContext = ck; } return result; }
  function invalidateRulesCache() { rulesCache = null; rulesCacheContext = ''; rulesLoad = null; }
  async function saveRule(rule) { const dKey = keyDomain(rule.domain), pKey = keyPage(rule.domain, rule.path || '/'); const old = await chrome.storage.local.get({ [dKey]: [], [pKey]: [] }); await chrome.storage.local.set({ [keyRule(rule.ruleId)]: rule, [dKey]: [...new Set([...(old[dKey] || []), rule.ruleId])], [pKey]: [...new Set([...(old[pKey] || []), rule.ruleId])] }); if (contextKey() === `${rule.domain}|${rule.path || '/'}`) { const current = rulesCache || []; rulesCache = [...current.filter(r => r.ruleId !== rule.ruleId), rule]; rulesCacheContext = contextKey(); } return rule; }
  async function updateRule(rule) { const updated = { ...rule, updatedAt: new Date().toISOString() }; await chrome.storage.local.set({ [keyRule(updated.ruleId)]: updated }); if (rulesCache && rulesCacheContext === contextKey()) rulesCache = rulesCache.map(r => r.ruleId === updated.ruleId ? updated : r); return updated; }
  async function deleteRule(id) { const rule = await getRule(id); if (!rule) return; await chrome.storage.local.remove(keyRule(id)); const dKey = keyDomain(rule.domain), pKey = keyPage(rule.domain, rule.path || '/'); const old = await chrome.storage.local.get({ [dKey]: [], [pKey]: [] }); await chrome.storage.local.set({ [dKey]: (old[dKey] || []).filter(x => x !== id), [pKey]: (old[pKey] || []).filter(x => x !== id) }); if (rulesCache) rulesCache = rulesCache.filter(r => r.ruleId !== id); }
  const stableToken = value => value && !(/^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(value) || /^[a-f0-9]{10,}$/i.test(value) || /(\d{9,}|\d{4,}_\d{4,})$/.test(value));
  const stableTokens = tokens => (tokens || []).filter(stableToken);
  async function sha256(value) { const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value)); return [...new Uint8Array(digest)].map(b => b.toString(16).padStart(2, '0')).join(''); }
  function normalizeText(value) { return String(value || '').replace(/\s+/g, ' ').trim().slice(0, 2000); }
  function volatileText(value) { const s = normalizeText(value); return !s || s.length > 1200 || /\b(?:\d{4,}|[A-F0-9]{12,})\b/i.test(s); }
  const attrNames = /^(data-|aria-|name$|role$|type$|href$|inputmode$|rel$|target$)/i;
  const rawAttrs = new Set(['role', 'type', 'inputmode', 'rel', 'target']);
  async function semanticAttrs(el) { const out = []; for (const a of el.attributes || []) { if (!attrNames.test(a.name) || !a.value) continue; const name = a.name.toLowerCase(); out.push({ name, valueKind: rawAttrs.has(name) ? 'structural' : 'hash', value: rawAttrs.has(name) ? a.value.toLowerCase() : await sha256(a.value.toLowerCase()) }); } return out; }
  function cssPathFor(el) { const parts = []; let cur = el, depth = 0; while (cur instanceof Element && cur !== document.documentElement && depth++ < 8) { const tag = cur.tagName.toLowerCase(), id = stableToken(cur.id) ? cur.id : ''; if (id) { parts.unshift(`#${CSS.escape(id)}`); break; } const classes = stableTokens(String(cur.className || '').split(/\s+/).filter(Boolean)).slice(0, 2); let part = tag; if (classes.length) part += `.${classes.map(CSS.escape).join('.')}`; const siblings = cur.parentElement ? [...cur.parentElement.children].filter(x => x.tagName === cur.tagName) : []; if (siblings.length > 1) part += `:nth-of-type(${siblings.indexOf(cur) + 1})`; parts.unshift(part); cur = cur.parentElement; } return parts.join('>'); }
  async function fingerprint(el) { const ids = stableTokens([el.id]), classes = stableTokens(String(el.className || '').split(/\s+/).filter(Boolean)), attrs = await semanticAttrs(el), text = normalizeText(el.textContent || ''); const fp = { generationVersion: '1.5', cssSelector: cssPathFor(el), stableId: ids[0] ? { value: ids[0] } : undefined, semanticAttributes: attrs, stableClasses: classes.map(className => ({ className })), tagName: el.tagName.toLowerCase() }; if (!volatileText(text)) fp.normalizedTextHash = { algorithm: 'SHA-256', hash: await sha256(text), stable: true }; const chain = []; let p = el.parentElement, depth = 0; while (p && depth++ < 4) { chain.push({ tag: p.tagName.toLowerCase(), stableClasses: stableTokens(String(p.className || '').split(/\s+/).filter(Boolean)) }); p = p.parentElement; } fp.ancestorContext = { chain, depthCaptured: chain.length }; const parent = el.parentElement, siblings = parent ? [...parent.children] : [], i = siblings.indexOf(el); fp.structureContext = { siblingSignature: { previousTag: i > 0 ? siblings[i - 1].tagName.toLowerCase() : undefined, nextTag: i >= 0 && i < siblings.length - 1 ? siblings[i + 1].tagName.toLowerCase() : undefined, indexWithinStableParent: i >= 0 ? i : undefined }, childSignature: { stableChildTagsTopK: [...new Set([...el.children].slice(0, 5).map(x => x.tagName.toLowerCase()))].slice(0, 3) } }; const r = el.getBoundingClientRect(), vw = Math.max(innerWidth, 1), vh = Math.max(innerHeight, 1); fp.geometricHint = { viewportXRatio: Math.max(0, Math.min(1, r.x / vw)), viewportYRatio: Math.max(0, Math.min(1, r.y / vh)), widthRatio: Math.max(0, Math.min(1, r.width / vw)), heightRatio: Math.max(0, Math.min(1, r.height / vh)) }; return fp; }
  function eqAttrs(a, b) { return a.name === b.name && a.valueKind === b.valueKind && a.value === b.value; }
  async function score(fp, el, cssMatched) { const attrs = await semanticAttrs(el), id = fp.stableId && el.id === fp.stableId.value ? 1 : 0, semantic = fp.semanticAttributes?.length ? fp.semanticAttributes.filter(x => attrs.some(y => eqAttrs(x, y))).length / fp.semanticAttributes.length : 0, text = fp.normalizedTextHash && !volatileText(el.textContent) && await sha256(normalizeText(el.textContent)) === fp.normalizedTextHash.hash ? 1 : 0, classes = fp.stableClasses?.length ? fp.stableClasses.filter(x => stableTokens(String(el.className || '').split(/\s+/)).includes(x.className)).length / fp.stableClasses.length : 0; let parent = el.parentElement, ancestor = 0, depth = 0; for (const expected of fp.ancestorContext?.chain || []) { if (!parent || depth++ >= 4) break; if (parent.tagName.toLowerCase() === expected.tag && expected.stableClasses.every(c => stableTokens(String(parent.className || '').split(/\s+/)).includes(c))) ancestor += 1; parent = parent.parentElement; } ancestor = fp.ancestorContext?.chain?.length ? ancestor / fp.ancestorContext.chain.length : 0; const i = el.parentElement ? [...el.parentElement.children].indexOf(el) : -1, expectedIndex = fp.structureContext?.siblingSignature?.indexWithinStableParent, structureAvailable = Number.isInteger(expectedIndex) && expectedIndex >= 0, structure = structureAvailable && expectedIndex === i ? 1 : 0, css = cssMatched ? 1 : 0, r = el.getBoundingClientRect(), g = fp.geometricHint; const geometry = g ? Math.max(0, 1 - (Math.abs(r.x / Math.max(innerWidth, 1) - g.viewportXRatio) + Math.abs(r.y / Math.max(innerHeight, 1) - g.viewportYRatio) + Math.abs(r.width / Math.max(innerWidth, 1) - g.widthRatio) + Math.abs(r.height / Math.max(innerHeight, 1) - g.heightRatio)) / 4) : 0, tag = fp.tagName === el.tagName.toLowerCase() ? 1 : 0; const parts = { stableId: { score: id, available: !!fp.stableId }, semanticAttributes: { score: semantic, available: !!fp.semanticAttributes?.length }, textHash: { score: text, available: !!fp.normalizedTextHash }, stableClasses: { score: classes, available: !!fp.stableClasses?.length }, ancestorContext: { score: ancestor, available: !!fp.ancestorContext?.chain?.length }, structureContext: { score: structure, available: structureAvailable }, cssSelector: { score: css, available: true }, geometry: { score: geometry, available: !!g }, tagName: { score: tag, available: true } }; let total = 0, available = 0; for (const [k, v] of Object.entries(parts)) if (v.available) { total += WEIGHTS[k] * v.score; available += WEIGHTS[k]; } const independent = INDEPENDENT.filter(k => parts[k].available && parts[k].score >= .65).length; return { element: el, totalScore: available ? total / available : 0, independent, parts }; }
  const shadowRoots = new Set();
  function collectShadowRoots() { const roots = [document]; const visit = root => { for (const el of root.querySelectorAll('*')) if (el.shadowRoot && !shadowRoots.has(el.shadowRoot)) { shadowRoots.add(el.shadowRoot); roots.push(el.shadowRoot); visit(el.shadowRoot); } }; visit(document); for (const root of shadowRoots) if (!roots.includes(root)) roots.push(root); return roots; }
  function queryAll(selector) { const out = []; for (const root of collectShadowRoots()) { try { out.push(...root.querySelectorAll(selector)); } catch (_) {} } return out; }
  async function match(fp) { const set = new Set(), cssSet = new WeakSet(); if (fp.cssSelector) queryAll(fp.cssSelector).forEach(el => { set.add(el); cssSet.add(el); }); if (fp.stableId?.value) queryAll(`#${CSS.escape(fp.stableId.value)}`).forEach(el => set.add(el)); for (const a of fp.semanticAttributes || []) if (a.valueKind === 'structural') queryAll(`[${CSS.escape(a.name)}="${CSS.escape(a.value)}"]`).forEach(el => set.add(el)); if (!set.size) queryAll(fp.tagName || '*').slice(0, MAX_CANDIDATES).forEach(el => set.add(el)); const ranked = []; for (const el of set) { ranked.push(await score(fp, el, cssSet.has(el))); if (ranked.length >= MAX_CANDIDATES) break; } ranked.sort((a, b) => b.totalScore - a.totalScore || b.independent - a.independent); const a = ranked[0], b = ranked[1]; if (!a || a.totalScore < .6) return { status: 'notFound', confidence: a?.totalScore || 0, selected: a }; if (a.totalScore < SAFETY_MIN_CONFIDENCE || a.independent < SAFETY_MIN_INDEPENDENT || (b && Math.abs(a.totalScore - b.totalScore) <= .05)) return { status: 'ambiguous', confidence: a.totalScore, selected: a }; return { status: 'active', confidence: a.totalScore, selected: a }; }
  let styleReady = false;
  function ensureStyle() { if (styleReady || document.getElementById(STYLE_ID)) { styleReady = true; return; } const style = document.createElement('style'); style.id = STYLE_ID; style.textContent = `.pb-effect-base{transition:filter 120ms ease}.pb-effect-blur{filter:blur(var(--pb-blur,6px))!important}.pb-effect-strongBlur{filter:blur(var(--pb-strong-blur,16px))!important}.pb-effect-pixelate{filter:blur(8px) contrast(1.8)!important}.pb-effect-blackout{filter:brightness(0)!important;color:transparent!important;text-shadow:none!important}.pb-effect-hide{visibility:hidden!important}`; (document.head || document.documentElement).appendChild(style); styleReady = true; }
  const original = new WeakMap(), applied = new Map();
  function apply(el, rule) { if (!(el instanceof Element)) return; ensureStyle(); if (!original.has(el)) original.set(el, { filter: el.style.filter, visibility: el.style.visibility, color: el.style.color, textShadow: el.style.textShadow, blur: el.style.getPropertyValue('--pb-blur'), strong: el.style.getPropertyValue('--pb-strong-blur') }); const px = Math.max(0, Math.min(100, Number(rule.intensity ?? 60))); EFFECT_CLASSES.slice(1).forEach(c => el.classList.remove(c)); el.classList.add('pb-effect-base', `pb-effect-${rule.effect || 'blur'}`); el.style.setProperty('--pb-blur', `${Math.max(1, Math.round(px / 100 * 12))}px`); el.style.setProperty('--pb-strong-blur', `${Math.max(4, Math.round(px / 100 * 28))}px`); el.setAttribute(ATTR, rule.ruleId); applied.set(rule.ruleId, el); }
  function removeElement(el) { if (!(el instanceof Element)) return; EFFECT_CLASSES.forEach(c => el.classList.remove(c)); const o = original.get(el); if (o) { if (o.filter) el.style.setProperty('filter', o.filter); else el.style.removeProperty('filter'); if (o.visibility) el.style.setProperty('visibility', o.visibility); else el.style.removeProperty('visibility'); if (o.color) el.style.setProperty('color', o.color); else el.style.removeProperty('color'); if (o.textShadow) el.style.setProperty('text-shadow', o.textShadow); else el.style.removeProperty('text-shadow'); if (o.blur) el.style.setProperty('--pb-blur', o.blur); else el.style.removeProperty('--pb-blur'); if (o.strong) el.style.setProperty('--pb-strong-blur', o.strong); else el.style.removeProperty('--pb-strong-blur'); original.delete(el); } el.removeAttribute(ATTR); }
  function removeRule(id) { const el = applied.get(id); if (el) removeElement(el); applied.delete(id); if (!el) queryAll(`[${ATTR}="${CSS.escape(id)}"]`).forEach(removeElement); }
  function removeAll() { applied.clear(); queryAll(`[${ATTR}]`).forEach(removeElement); }
  function effectIsIntact(el, rule) { if (!(el instanceof Element) || !el.isConnected) return false; return el.getAttribute(ATTR) === rule.ruleId && el.classList.contains('pb-effect-base') && el.classList.contains(`pb-effect-${rule.effect || 'blur'}`); }
  let integrityFrame = 0, integrityQueued = false;
  async function checkAppliedIntegrity() { integrityFrame = 0; integrityQueued = false; if (!(await getSettings()).extensionEnabled || !applied.size) return; const rules = await getRules(), byId = new Map(rules.map(r => [r.ruleId, r])), missing = []; for (const [id, el] of applied) { const rule = byId.get(id); if (!rule || pageSuppressed.has(id)) continue; if (!effectIsIntact(el, rule)) missing.push([el, rule]); } for (const [el, rule] of missing) { if (el.isConnected) apply(el, rule); else queueEvaluate(0); } }
  function queueIntegrityCheck() { if (integrityQueued) return; integrityQueued = true; if (typeof requestAnimationFrame === 'function') integrityFrame = requestAnimationFrame(checkAppliedIntegrity); else integrityFrame = setTimeout(checkAppliedIntegrity, 0); }
  let selection = false, hover = null, retryTimer = null, evaluating = false, evaluateQueued = false, selecting = false;
  let selectionJobs = 0;
  let selectionQueue = Promise.resolve();
  const retryCounts = new Map(), pageSuppressed = new Set();
  function removeIndicator() { const el = document.getElementById(INDICATOR_ID); if (el) el.remove(); }
  function showIndicator() { removeIndicator(); const el = document.createElement('div'); el.id = INDICATOR_ID; el.setAttribute('data-progettoblur-ui', 'true'); const label = document.createElement('span'); label.textContent = 'Selezione attiva: clicca sugli elementi da oscurare (Esc per terminare)'; const btn = document.createElement('button'); btn.type = 'button'; btn.textContent = 'Termina selezione'; btn.addEventListener('click', e => { e.preventDefault(); e.stopPropagation(); e.stopImmediatePropagation(); stopSelection(); }, true); el.append(label, btn); (document.body || document.documentElement).appendChild(el); }
  function stopSelection() { selection = false; selecting = false; document.removeEventListener('mousemove', onMove, true); document.removeEventListener('click', onClick, true); document.removeEventListener('keydown', onKey, true); if (hover) hover.classList.remove(HIGHLIGHT); hover = null; removeIndicator(); selectionQueue.finally(() => { if (!selection && selectionJobs === 0) queueEvaluate(0); }); }
  function target(t) { if (!(t instanceof Element) || t.id === STYLE_ID || t.closest('[data-progettoblur-ui="true"]')) return null; return t; }
  function onMove(e) { const raw = target(e.target); if (!selection || !raw) return; const chooser = globalThis.__stayBlurChooseTarget; const t = typeof chooser === 'function' ? chooser(raw) : raw; if (!t) return; if (hover) hover.classList.remove(HIGHLIGHT); hover = t; hover.classList.add(HIGHLIGHT); }
  async function createSelectionRule(t) { selectionJobs += 1; selecting = true; try { const c = context(), now = new Date().toISOString(), settings = await getSettings(), allowedEffects = new Set(['blur', 'strongBlur', 'pixelate', 'blackout', 'hide']), effect = allowedEffects.has(settings.selectionEffect) ? settings.selectionEffect : 'blur', intensity = Math.max(0, Math.min(100, Number(settings.selectionIntensity ?? 60))); const rule = { ruleId: `rule-${crypto.randomUUID()}`, scope: 'page', domain: c.domain, path: c.path, url: location.href, frameKey: frameContextKey() || 'unknown', enabled: true, status: 'active', effect, intensity, createdAt: now, updatedAt: now, fingerprint: await fingerprint(t) }; await saveRule(rule); apply(t, rule); retryCounts.delete(rule.ruleId); } finally { selectionJobs = Math.max(0, selectionJobs - 1); selecting = selectionJobs > 0; if (!selection && selectionJobs === 0) queueEvaluate(0); } }
  function onClick(e) { const raw = target(e.target); if (!selection || !raw || raw.tagName === 'IFRAME') return; const chooser = globalThis.__stayBlurChooseTarget; const t = typeof chooser === 'function' ? chooser(raw) : raw; if (!t || t.tagName === 'IFRAME') return; if (t.closest(`[${ATTR}]`)) { e.preventDefault(); e.stopPropagation(); e.stopImmediatePropagation(); return; } e.preventDefault(); e.stopPropagation(); e.stopImmediatePropagation(); selectionQueue = selectionQueue.then(() => createSelectionRule(t)).catch(error => { console.error('[StayBlur] selection failed', error); }); }
  function onKey(e) { if (e.key === 'Escape') stopSelection(); }
  function startSelection() { stopSelection(); selection = true; document.addEventListener('mousemove', onMove, true); document.addEventListener('click', onClick, true); document.addEventListener('keydown', onKey, true); showIndicator(); }
  globalThis.__progettoBlurStartSelection = startSelection;
  globalThis.__progettoBlurStopSelection = stopSelection;
  async function persistStatus(rule, result) { if (rule.status === result.status && Math.abs(Number(rule.lastConfidence || 0) - Number(result.confidence || 0)) < .01) return; const updated = { ...rule, status: result.status, lastConfidence: result.confidence, statusContext: { domain: context().domain, path: context().path, evaluatedAt: new Date().toISOString() }, lastMatchedAt: result.status === 'active' ? new Date().toISOString() : rule.lastMatchedAt }; await updateRule(updated); }
  async function evaluateRule(rule) { if (!ruleAppliesToCurrentFrame(rule)) { removeRule(rule.ruleId); return { status: 'notApplicable', confidence: 0 }; } if (!rule.enabled || !(await getSettings()).extensionEnabled) { removeRule(rule.ruleId); return { status: 'disabled', confidence: 0 }; } if (pageSuppressed.has(rule.ruleId)) { removeRule(rule.ruleId); return { status: 'suppressed', confidence: 0 }; } const result = await match(rule.fingerprint); if (result.status === 'active' && result.selected?.element) apply(result.selected.element, rule); else removeRule(rule.ruleId); await persistStatus(rule, result); return result; }
  async function evaluateAll() { if (evaluating) { evaluateQueued = true; return; } evaluating = true; try { const rules = await getRules(); const results = await Promise.all(rules.map(async r => ({ rule: r, result: await evaluateRule(r) }))); const pending = results.filter(x => x.rule.enabled && !pageSuppressed.has(x.rule.ruleId) && (x.result.status === 'notFound' || x.result.status === 'ambiguous')).map(x => x.rule.ruleId); if (pending.length) scheduleRetries(pending); } finally { evaluating = false; if (evaluateQueued) { evaluateQueued = false; queueEvaluate(0); } } }
  function queueEvaluate(delay = 20) { clearTimeout(retryTimer); retryTimer = setTimeout(evaluateAll, delay); }
  function scheduleRetries(ids) { retryCounts.clear(); ids.forEach(id => retryCounts.set(id, 0)); queueRetry(ids); }
  function queueRetry(ids) { const pending = ids.filter(id => retryCounts.has(id)); if (!pending.length) return; const next = Math.min(...pending.map(id => retryCounts.get(id) || 0)); const delay = RETRY_DELAYS[Math.min(next, RETRY_DELAYS.length - 1)]; clearTimeout(retryTimer); retryTimer = setTimeout(async () => { for (const id of pending) retryCounts.set(id, (retryCounts.get(id) || 0) + 1); await evaluateAll(); }, delay); }
  const observedRoots = new Set();
  function observeRoot(root) { if (!root || observedRoots.has(root)) return; const observer = new MutationObserver(mutations => { let added = false, integrity = false; for (const mutation of mutations) { if (mutation.type === 'childList' && mutation.addedNodes.length) added = true; if (mutation.type === 'attributes' && mutation.target instanceof Element && applied.has(mutation.target)) integrity = true; } if (integrity) queueIntegrityCheck(); if (added) { collectShadowRoots(); observeAllRoots(); if (!evaluating) queueEvaluate(20); else evaluateQueued = true; } }); observer.observe(root, { childList: true, subtree: true, attributes: true, attributeFilter: INTEGRITY_ATTRS }); observedRoots.add(root); }
  function observeAllRoots() { collectShadowRoots().forEach(observeRoot); }
  chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => { (async () => { switch (message?.type) { case 'BG_ENTER_SELECTION': startSelection(); break; case 'BG_EXIT_SELECTION': stopSelection(); break; case 'BG_REMOVE_RULE_EFFECT_PAGE': pageSuppressed.add(message.ruleId); retryCounts.delete(message.ruleId); removeRule(message.ruleId); break; case 'BG_REMOVE_ALL_EFFECTS_PAGE': { const rules = await getRules(); rules.forEach(r => pageSuppressed.add(r.ruleId)); retryCounts.clear(); removeAll(); break; } case 'BG_RETRY_RULE_ON_PAGE': { pageSuppressed.delete(message.ruleId); retryCounts.delete(message.ruleId); const r = await getRule(message.ruleId); if (r) await evaluateRule(r); break; } case 'POPUP_DISABLE_RULE': { const r = await getRule(message.ruleId); if (r) { r.enabled = false; r.status = 'disabled'; pageSuppressed.delete(r.ruleId); await updateRule(r); removeRule(r.ruleId); } break; } case 'POPUP_ENABLE_RULE': { const r = await getRule(message.ruleId); if (r) { r.enabled = true; pageSuppressed.delete(r.ruleId); retryCounts.delete(r.ruleId); await updateRule(r); await evaluateRule(r); } break; } case 'POPUP_DELETE_RULE': pageSuppressed.delete(message.ruleId); retryCounts.delete(message.ruleId); removeRule(message.ruleId); await deleteRule(message.ruleId); break; case 'CONTENT_GET_STATE': { const settings = await getSettings(); sendResponse({ ok: true, extensionEnabled: settings.extensionEnabled !== false, selectionActive: selection, rules: await getRules() }); return; } default: break; } sendResponse({ ok: true }); })().catch(err => sendResponse({ ok: false, error: String(err?.message || err) })); return true; });
  function installSpaHooks() { for (const name of ['pushState', 'replaceState']) { const originalFn = history[name]; if (originalFn.__progettoBlurWrapped) continue; const wrapped = function (...args) { const before = location.href, result = originalFn.apply(this, args); if (location.href !== before) { retryCounts.clear(); pageSuppressed.clear(); invalidateRulesCache(); clearTimeout(retryTimer); evaluateAll(); } return result; }; Object.defineProperty(wrapped, '__progettoBlurWrapped', { value: true }); history[name] = wrapped; } addEventListener('popstate', () => { retryCounts.clear(); pageSuppressed.clear(); invalidateRulesCache(); clearTimeout(retryTimer); evaluateAll(); }, true); }
  chrome.storage.onChanged.addListener(changes => { if (changes[SETTINGS_KEY]) { settingsCache = { extensionEnabled: true, selectionEffect: 'blur', selectionIntensity: 60, ...(changes[SETTINGS_KEY].newValue || {}) }; settingsReady = true; if (settingsCache.extensionEnabled === false) removeAll(); else if (!selection && selectionJobs === 0) queueEvaluate(0); } if (Object.keys(changes).some(k => k.startsWith(RULE_PREFIX) || k.startsWith('idx:'))) { if (selection || selectionJobs > 0) return; invalidateRulesCache(); queueEvaluate(0); } });
  installSpaHooks(); collectShadowRoots(); observeAllRoots(); evaluateAll();
})();
