(() => {
  'use strict';
  const RULE_ATTR='data-progettoblur-rule-id',OVERLAY_ID='stayblur-rule-focus-overlay',RULE_PREFIX='rule:';
  let overlay=null,focused=null,timer=0;
  const stable=v=>{const s=String(v||'').trim();return !!s&&!/^[a-f0-9]{8}-[a-f0-9-]{27,}$/i.test(s)&&!/^[a-f0-9]{10,}$/i.test(s)&&!/(\d{9,}|\d{4,}_\d{4,})$/.test(s)};
  const tokens=v=>String(v||'').split(/\s+/).filter(stable);
  const norm=v=>String(v||'').replace(/\s+/g,' ').trim().slice(0,1200);
  const esc=v=>CSS.escape(String(v));
  async function getRule(id){const r=await chrome.storage.local.get({[RULE_PREFIX+id]:null});return r[RULE_PREFIX+id]||null}
  function ensureStyle(){if(document.getElementById('stayblur-focus-effect-style'))return;const s=document.createElement('style');s.id='stayblur-focus-effect-style';s.textContent='.pb-effect-base{transition:filter 120ms ease}.pb-effect-blur{filter:blur(var(--pb-blur,6px))!important}.pb-effect-strongBlur{filter:blur(var(--pb-strong-blur,16px))!important}.pb-effect-pixelate{filter:blur(8px) contrast(1.8)!important}.pb-effect-blackout{filter:brightness(0)!important;color:transparent!important;text-shadow:none!important}.pb-effect-hide{visibility:hidden!important}';(document.head||document.documentElement).appendChild(s)}
  function applyEffect(el,rule){ensureStyle();const effect=['blur','strongBlur','pixelate','blackout','hide'].includes(rule.effect)?rule.effect:'blur',i=Math.max(0,Math.min(100,Number(rule.intensity??60)));['blur','strongBlur','pixelate','blackout','hide'].forEach(n=>el.classList.remove(`pb-effect-${n}`));el.classList.add('pb-effect-base',`pb-effect-${effect}`);el.style.setProperty('--pb-blur',`${Math.max(1,Math.round(i*.12))}px`);el.style.setProperty('--pb-strong-blur',`${Math.max(4,Math.round(i*.28))}px`);el.setAttribute(RULE_ATTR,rule.ruleId)}
  function collect(rule){const fp=rule.fingerprint||{},out=[],seen=new Set(),add=els=>{for(const el of els)if(el instanceof Element&&!seen.has(el)){seen.add(el);out.push(el)}};
    try{add(document.querySelectorAll(`[${RULE_ATTR}="${esc(rule.ruleId)}"]`))}catch(_){} if(out.length)return out;
    if(fp.stableId){try{const byId=[...document.querySelectorAll(`#${esc(fp.stableId)}`)];if(byId.length===1)return byId}catch(_){}
    if(fp.cssSelector){try{const byCss=[...document.querySelectorAll(fp.cssSelector)];if(byCss.length===1)return byCss}catch(_){}
    }
    for(const a of fp.semanticAttributes||[]){try{add(document.querySelectorAll(`[${esc(a.name)}="${CSS.escape(a.value)}"]`))}catch(_) {}}
    if(fp.tagName&&fp.text){for(const el of document.getElementsByTagName(fp.tagName)){if(norm(el.textContent)===fp.text)add([el])}}
    if(!out.length&&fp.tagName){try{add(document.getElementsByTagName(fp.tagName))}catch(_) {}}
    return out;
  }
  function score(fp,el){let v=0,ind=0;if(fp.stableId&&el.id===fp.stableId){v+=.5;ind++}const cs=fp.stableClasses||[];if(cs.length){const hit=cs.filter(c=>tokens(el.className).includes(c)).length/cs.length;if(hit>=.5){v+=.18*hit;ind++}}const as=fp.semanticAttributes||[];if(as.length){const hit=as.filter(a=>el.getAttribute(a.name)?.toLowerCase()===String(a.value).toLowerCase()).length/as.length;if(hit>=.5){v+=.2*hit;ind++}}if(fp.tagName===el.tagName.toLowerCase())v+=.06;if(fp.parentTag===el.parentElement?.tagName.toLowerCase())v+=.05;const pc=fp.parentClasses||[];if(pc.length){const hit=pc.filter(c=>tokens(el.parentElement?.className).includes(c)).length/pc.length;if(hit>=.5){v+=.06;ind++}}if(Number.isInteger(fp.siblingIndex)&&fp.siblingIndex===[...(el.parentElement?.children||[])].indexOf(el)){v+=.08;ind++}if(fp.text&&fp.text.length<=600&&norm(el.textContent)===fp.text){v+=.2;ind++}return{v:Math.min(1,v),ind}}
  function choose(rule){const fp=rule.fingerprint||{},all=collect(rule);if(!all.length)return null;if(all.length===1)return all[0];let best=null,second=null;for(const el of all){const s=score(fp,el),item={el,...s};if(!best||item.v>best.v){second=best;best=item}else if(!second||item.v>second.v)second=item}const gap=second?best.v-second.v:1;return best&&best.v>=.62&&best.ind>=2&&gap>.06?best.el:null}
  function clear(){if(timer)clearTimeout(timer);timer=0;if(overlay)overlay.remove();overlay=null;focused=null}
  function update(){if(!overlay||!focused||!focused.isConnected){clear();return}const r=focused.getBoundingClientRect();Object.assign(overlay.style,{left:`${Math.round(r.left-3)}px`,top:`${Math.round(r.top-3)}px`,width:`${Math.max(0,Math.round(r.width+6))}px`,height:`${Math.max(0,Math.round(r.height+6))}px`})}
  function show(el){clear();focused=el;overlay=document.createElement('div');overlay.id=OVERLAY_ID;overlay.setAttribute('data-progettoblur-ui','true');Object.assign(overlay.style,{position:'fixed',pointerEvents:'none',zIndex:'2147483647',border:'3px solid #1769d1',borderRadius:'3px',boxShadow:'0 0 0 5px rgba(23,105,209,.22)',boxSizing:'border-box'});(document.body||document.documentElement).appendChild(overlay);update();addEventListener('scroll',update,true);addEventListener('resize',update,true);timer=setTimeout(()=>{removeEventListener('scroll',update,true);removeEventListener('resize',update,true);clear()},3500)}
  chrome.runtime.onMessage.addListener((message,_sender,sendResponse)=>{if(message?.type!=='BG_FOCUS_RULE_OVERLAY')return;(async()=>{const rule=await getRule(message.ruleId);if(!rule)return sendResponse({ok:true,result:false});const el=choose(rule);if(!el)return sendResponse({ok:true,result:false});applyEffect(el,rule);try{el.scrollIntoView({behavior:'smooth',block:'center',inline:'nearest'})}catch(_){el.scrollIntoView()}show(el);sendResponse({ok:true,result:true})})().catch(e=>sendResponse({ok:false,error:String(e?.message||e)}));return true});
})();
