(() => {
  'use strict';
  const RULE_ATTR='data-progettoblur-rule-id';
  const EFFECT_CLASSES=['pb-effect-base','pb-effect-blur','pb-effect-strongBlur','pb-effect-pixelate','pb-effect-blackout','pb-effect-hide'];
  let restoreQueue=null;
  function snapshotEffects(){const snapshots=[];document.querySelectorAll(`[${RULE_ATTR}]`).forEach(el=>{if(!(el instanceof Element))return;snapshots.push({el,classNames:EFFECT_CLASSES.filter(n=>el.classList.contains(n)),blur:el.style.getPropertyValue('--pb-blur'),strongBlur:el.style.getPropertyValue('--pb-strong-blur'),filter:el.style.getPropertyValue('filter'),visibility:el.style.getPropertyValue('visibility'),color:el.style.getPropertyValue('color'),textShadow:el.style.getPropertyValue('text-shadow'),ruleId:el.getAttribute(RULE_ATTR)});});return snapshots}
  function restoreEffects(snapshots){for(const item of snapshots){const el=item.el;if(!el.isConnected)continue;EFFECT_CLASSES.forEach(n=>el.classList.remove(n));item.classNames.forEach(n=>el.classList.add(n));if(item.blur)el.style.setProperty('--pb-blur',item.blur);else el.style.removeProperty('--pb-blur');if(item.strongBlur)el.style.setProperty('--pb-strong-blur',item.strongBlur);else el.style.removeProperty('--pb-strong-blur');if(item.filter)el.style.setProperty('filter',item.filter);else el.style.removeProperty('filter');if(item.visibility)el.style.setProperty('visibility',item.visibility);else el.style.removeProperty('visibility');if(item.color)el.style.setProperty('color',item.color);else el.style.removeProperty('color');if(item.textShadow)el.style.setProperty('text-shadow',item.textShadow);else el.style.removeProperty('text-shadow');if(item.ruleId)el.setAttribute(RULE_ATTR,item.ruleId)}}
  function scheduleRestore(delay){setTimeout(()=>{if(restoreQueue)restoreEffects(restoreQueue)},delay)}
  addEventListener('keydown',event=>{if(event.key!=='Escape')return;const snapshots=snapshotEffects();if(!snapshots.length)return;restoreQueue=snapshots;scheduleRestore(0);scheduleRestore(120);scheduleRestore(400);scheduleRestore(900);setTimeout(()=>{restoreQueue=null},1200)},true);
})();
